version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: onehappyfellow
      POSTGRES_PASSWORD: learnkorean
      POSTGRES_DB: daebak
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
